### PR TITLE
Refactor: Implement toString() via ToStringBuilder in data xfer objects.

### PR DESCRIPTION
**Pull request by apetro**
Incidentally sets stage for cleanly changing the data transfer objects (data model) with cogent changes to toString() method implementations.

### CODE REVIEW

**Comment by drewwills** [comment]
@apetro -- What about a reflection-based ToStringBuilder;  It seems very easy to forget to manage the treatment of new fields in toString() over time.  [(ReflectionToStringBuilder)](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/ReflectionToStringBuilder.html)

**Comment by apetro** [comment]
It is indeed easy to fail to maintain `toString()` implementations, though not more so when using `ToStringBuilder` rather than hand crafted `toString()`s.

`ReflectionToStringBuilder` has some abstract risks around the security manager environment in which it might be running. It's probably nonetheless fine to use.

**Comment by andrewstuart** [comment]
Is there a preprocessing-based approach that can generate the appropriate code at compile time, rather than incurring the overhead of reflection?

That seems most easy and efficient, unless we're expecting these classes to be subclassed without any necessary changes to `toString()`.

**Comment by apetro** [comment]
@drewwills @andrewstuart You're over-thinking this. :smile: Status quo is ad-hoc `toString()` implementations. Idiomatic use of `ToStringBuilder` is slightly better. Accept the better, and seek more better later. 

#29 offers this `ToStringBuilder` refactor again, except against latest `Soffit`.

**Comment by andrewstuart** [comment]
I'm certainly all for baby steps, but if there's a baby step after this that can be that _last_ baby step, I'd certainly love to see that.

**Pull request closed without merging**
